---
- name: Configure macOS
  hosts: all
  become: false

  vars_files: default.config.yml

  pre_tasks:
    - name: Include playbook configuration
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

    - name: Store non-root user home directory
      set_fact:
        dotfiles_repo_local_destination: "{{ ansible_env.HOME }}{{ dotfiles_repo_local_destination | regex_replace('^~', '') }}"
      when: dotfiles_repo_local_destination is defined and dotfiles_repo_local_destination.startswith('~')
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools

    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']

    - role: geerlingguy.mac.mas
      when: >
          (mas_installed_apps | default([]) | length > 0) or
          (mas_installed_app_ids | default([]) | length > 0)
      tags: ['mas']

    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ ansible_user_id }}"

    - role: geerlingguy.dotfiles
      when: configure_dotfiles | default(false)
      tags: ['dotfiles']

  tasks:
    - import_tasks: tasks/ruby.yml
      when: configure_ruby | default(false)
      tags: ['ruby']

    - import_tasks: tasks/python.yml
      when: configure_python | default(false)
      tags: ['python']

    - import_tasks: tasks/node.yml
      when: configure_node | default(false)
      tags: ['node']

    - import_tasks: tasks/osx.yml
      tags: ['osx']

    - import_tasks: tasks/iterm2.yml
      when: configure_iterm2 | default(false)
      tags: ['iterm2']

    - name: Run configured post-provision ansible task files
      include_tasks:
        file: "{{ outer_item }}"
        apply:
          tags: ['post']
      with_fileglob: "{{ post_provision_tasks | default([]) }}"
      loop_control:
        loop_var: outer_item
      tags: ['post']

  post_tasks:
    - name: Fix permission issues with ZSH's compinit
      shell: compaudit | xargs chmod g-w
      when: ansible_env['SHELL'] == '/bin/zsh'
      tags: ['post']