---
- name: Ensure iterm2 is installed
  ansible.builtin.stat:
    path: "/Applications/iTerm.app"
  register: iterm2_stat

- name: Ensure iterm2 preferences folder exists
  ansible.builtin.file:
    path: "{{ iterm2_preferences_destination }}"
    state: directory
    mode: "0755"
  when:
    - iterm2_stat.stat.exists
    - iterm2_preferences_destination is defined

- name: Copy iterm2 preferences file
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/files/iterm2/com.googlecode.iterm2.plist"
    dest: "{{ iterm2_preferences_destination }}/com.googlecode.iterm2.plist"
    mode: "0644"
    force: false
  when: iterm2_stat.stat.exists

- name: Ensure Fonts directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Library/Fonts"
    state: directory
    mode: "0755"

- name: Ensure fonts are installed
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/Library/Fonts/{{ item | basename }}"
    mode: "0644"
  loop: "{{ iterm2_fonts }}"
  when:
    - iterm2_stat.stat.exists
    - iterm2_fonts is defined
    - iterm2_fonts | length > 0

- name: Ensure preferences are loaded from a custom folder
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - key: "PrefsCustomFolder"
      type: "string"
      value: "{{ iterm2_preferences_destination }}"
    - key: "LoadPrefsFromCustomFolder"
      type: "bool"
      value: true
  when:
    - iterm2_stat.stat.exists
    - iterm2_preferences_destination | default('') | length > 0

- name: Check if current shell is supported
  ansible.builtin.set_fact:
    shell_is_supported: "{{ ansible_env.SHELL | basename in ['bash', 'zsh', 'fish', 'tcsh'] }}"

- name: Check if shell integration is already installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.iterm2_shell_integration.zsh"
  register: shell_integration

- name: Download shell integration script
  ansible.builtin.uri:
    url: https://iterm2.com/misc/install_shell_integration.sh
    return_content: true
  register: shell_integration_script
  when:
    - iterm2_stat.stat.exists
    - not shell_integration.stat.exists
    - shell_is_supported

- name: Install shell integration
  ansible.builtin.command: "{{ shell_integration_script.content }}"
  register: shell_integration_result
  changed_when: shell_integration_result.rc == 0
  when:
    - iterm2_stat.stat.exists
    - not shell_integration.stat.exists
    - shell_integration_script is defined
    - shell_is_supported
