---
- name: Ensure iTerm2 is installed
  stat:
    path: "/Applications/iTerm.app"
  register: iterm2_stat

- name: Copy iTerm2 preferences file
  copy:
    src: "{{ playbook_dir }}/files/iterm2/com.googlecode.iterm2.plist"
    dest: "{{ iterm2_preferences_destination }}"
  when: iterm2_stat.stat.exists

- name: Ensure fonts are installed.
  get_url:
    url: "{{ item }}"
    dest: "~/Library/Fonts"
  with_items: "{{ iterm2_fonts }}"
  when: iterm2_fonts is defined

- name: Ensure preferences are loaded from a custom folder.
  command: "defaults write com.googlecode.iterm2 'PrefsCustomFolder' -string '{{ iterm2_preferences_destination }}'"
  when: iterm2_preferences_destination is defined and iterm2_preferences_destination

- name: Ensure shell integration is installed.
  shell: curl -L https://iterm2.com/misc/install_shell_integration.sh | bash
  args:
    warn: no
  when: iterm2_stat.stat.exists