---
- name: Set .osx file path variable
  ansible.builtin.set_fact:
    osx_file_path: "{{ dotfiles_repo_local_destination }}/.osx"

- name: Check that the .osx file exists
  ansible.builtin.stat:
    path: "{{ osx_file_path }}"
  register: osx_stat

- name: Ensuring execution permissions for .osx file
  ansible.builtin.file:
    dest: "{{ osx_file_path }}"
    mode: a+x
  when: osx_stat.stat.exists

- name: Check if .osx was previously run by checking for log file
  ansible.builtin.stat:
    path: /tmp/osx_setup.log
  register: osx_log_stat

- name: Run .osx dotfile
  ansible.builtin.shell: |
    set -x
    {{ osx_file_path }} --no-restart >> /tmp/osx_setup.log
  changed_when: true
  become: false
  when: osx_stat.stat.exists and not osx_log_stat.stat.exists
