---
- name: Make sure fnm is installed
  homebrew:
    name: fnm
    state: present

- name: Get latest LTS Node version
  shell: fnm ls-remote | grep -E 'lts' | tail -1 | awk '{print $1}' | tr -d '[:space:]'
  register: latest_lts_version
  changed_when: false
  environment:
    PATH: "/opt/homebrew/bin:{{ ansible_env.PATH }}"

- name: Get current default Node version
  shell: fnm current
  register: current_node_version
  changed_when: false
  failed_when: false
  environment:
    PATH: "/opt/homebrew/bin:{{ ansible_env.PATH }}"

- name: Install latest LTS Node version via fnm
  shell: fnm install --lts
  when: current_node_version.stdout != latest_lts_version.stdout
  environment:
    PATH: "/opt/homebrew/bin:{{ ansible_env.PATH }}"

- name: Set default to latest LTS
  shell: fnm default lts-latest
  when: current_node_version.stdout != latest_lts_version.stdout
  environment:
    PATH: "/opt/homebrew/bin:{{ ansible_env.PATH }}"