---
- name: Make sure fnm is installed
  homebrew:
    name: fnm
    state: present

- name: Get latest LTS Node version
  ansible.builtin.shell: fnm ls-remote --lts | tail -1 | awk '{print $1}'
  register: latest_lts_version
  changed_when: false
  environment:
    PATH: "/opt/homebrew/bin:{{ ansible_env.PATH }}"

- name: Get current default Node version
  ansible.builtin.command: fnm current
  register: current_node_version
  changed_when: false
  failed_when: false
  environment:
    PATH: "/opt/homebrew/bin:{{ ansible_env.PATH }}"

- name: Install latest LTS Node version via fnm
  ansible.builtin.command: fnm install --lts
  when: current_node_version.stdout != latest_lts_version.stdout
  environment:
    PATH: "/opt/homebrew/bin:{{ ansible_env.PATH }}"

- name: Set default to latest LTS
  ansible.builtin.command: fnm default lts-latest
  when: current_node_version.stdout != latest_lts_version.stdout
  environment:
    PATH: "/opt/homebrew/bin:{{ ansible_env.PATH }}"
