---
- name: Make sure pyenv is installed
  homebrew:
    name: pyenv
    state: present

- name: Install latest Python version via pyenv
  shell: |
    LATEST_PYTHON_VERSION="$(pyenv install -l | grep -v - | tail -1 | tr -d '[:space:]')"
    pyenv install "${LATEST_PYTHON_VERSION}"
    pyenv global "${LATEST_PYTHON_VERSION}"
    pyenv rehash