---
- name: Make sure rbenv is installed
  homebrew:
    name: rbenv
    state: present

- name: Make sure ruby-build is installed
  homebrew:
    name: ruby-build
    state: present

- name: Get latest available Ruby version
  shell: rbenv install -l | grep -v - | tail -1 | tr -d '[:space:]'
  register: latest_ruby_version
  changed_when: false

- name: Get current global Ruby version
  shell: rbenv global
  register: current_ruby_version
  changed_when: false
  failed_when: false

- name: Install latest Ruby version via rbenv
  shell: rbenv install "{{ latest_ruby_version.stdout }}" --skip-existing
  when: current_ruby_version.stdout != latest_ruby_version.stdout
  register: ruby_install

- name: Set global Ruby version to latest
  shell: rbenv global "{{ latest_ruby_version.stdout }}"
  when: current_ruby_version.stdout != latest_ruby_version.stdout

- name: Rehash rbenv shims
  shell: rbenv rehash
  when: ruby_install is changed