---
- name: Check if any Ruby version is installed
  command: rbenv versions
  register: ruby_versions

- name: Install latest Ruby version via rbenv
  shell: |
    LATEST_RUBY_VERSION="$(rbenv install -l | grep -v - | tail -1 | tr -d '[:space:]')"
    rbenv install "${LATEST_RUBY_VERSION}"
    rbenv global "${LATEST_RUBY_VERSION}"
    rbenv rehash
  when: ruby_versions.stdout == "system"