---
- name: Make sure rbenv is installed
  community.general.homebrew:
    name: rbenv
    state: present

- name: Make sure ruby-build is installed
  community.general.homebrew:
    name: ruby-build
    state: present

- name: Get latest available Ruby version
  ansible.builtin.shell: |
    set -o pipefail
    rbenv install -l | grep -v - | tail -1 | tr -d '[:space:]'
  register: ruby_latest_version
  changed_when: false

- name: Get current global Ruby version
  ansible.builtin.command: rbenv global
  register: ruby_current_version
  changed_when: false
  failed_when: false

- name: Install latest Ruby version via rbenv
  ansible.builtin.command:
    rbenv install "{{ latest_ruby_version.stdout }}" --skip-existing
  when: current_ruby_version.stdout != latest_ruby_version.stdout
  register: ruby_install
  changed_when: ruby_install.stdout | trim | length > 0
  notify:
    - Set global Ruby version to latest
    - Rehash rbenv shims
