---
name: CI
'on':
  pull_request:
  push:
    branches: [master]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v5
      - name: Lint YAML files
        uses: ibiqlik/action-yamllint@master
      - name: Run Ansible Lint
        uses: ansible/ansible-lint@main
      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: .ansible

  integration:
    name: Integration with Homebrew already installed in machine
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - macos-13
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v5

      - name: Uninstall CI runners' built-in browser installs
        run: |
          sudo rm -rf /Applications/Firefox.app
          sudo rm -rf /Applications/Google\ Chrome.app

      - name: Run the setup script
        run: ./setup.sh

  integration_homebrew_not_installed:
    name: Integration tests without Homebrew installed in machine
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          # - macos-13 this takes way too long
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v5

      - name: Uninstall CI runners' built-in browser installs
        run: |
          sudo rm -rf /Applications/Firefox.app
          sudo rm -rf /Applications/Google\ Chrome.app

      - name: Uninstall CI runners' built-in Homebrew.
        run: tests/uninstall_homebrew.sh

      - name: Run the setup script
        run: ./setup.sh
